### ISSUE TITLE
Integrate a code editor with solidity syntax

### ISSUE THREAD

**Issue by thibmeu** [blockchainworkbench/workbench-ui#16]
Blockchain workbench website uses Ace9.

**Comment by severus-sn4pe** [comment]
Integration of Ace in react with `react-ace` worked without problem. 
But to use the solidity syntax with `ace-mode-solidity` I had to create a fork with a minor change in order to get it running (see here: https://github.com/severus-sn4pe/ace-mode-solidity/commit/8aad050c642b4e27c16ff40845fd19b76fb5f106). Maybe there's a better solution for this?

~Static Site with Ace and Solidity can be found here: https://severus-sn4pe.github.io/workbench-ui/login~
