### ISSUE TITLE
Header for pages

### ISSUE THREAD

**Issue by thibmeu** [blockchainworkbench/workbench-ui#43]
Here is the current page header
![2019-04-17 09 51 00 blockchainworkbench com 2c8b2faf65db](https://user-images.githubusercontent.com/1894894/56274245-52ddce00-60f6-11e9-965c-37244d2fd1e6.png)

It doesn't contain any meaningful information about the page nor the category.

It should be designed with information related to its main category, such as:
+ Category title
+ Difficulty
+ Estimated time of completion
+ Last update
+ Source of the course / report something wrong

**Comment by thibmeu** [comment]
![Header_information](https://user-images.githubusercontent.com/1894894/56951812-a7d70680-6b30-11e9-8174-0b30f852486e.png)

Difficulty and time should have the same logo like as search feature

**Comment by severus-sn4pe** [comment]
What should happen, when someone clicks on `Author`?

Open an Author-Page and show all content written by this person?
We could parse all authors after the pages have been loaded from the jsonfeed and group them by Author.
or did you want to create additional "About author x" page for each author instead of build that page dynamically?

that should probably also be tracked in another issue

**Comment by severus-sn4pe** [comment]
@thibmeu should the `Overview`-Page add up the duration of each page of the category and display this sum?
